version: "3.7"
services:
  mysql-clean-quarkus:
    image: mysql:8.0
    container_name: mysql-clean-quarkus
    environment:
      - MYSQL_DATABASE=quarkus
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"